export { useClienteService } from './api/cliente.service'
export { useProcessoService } from './api/processo.service'
export { useTimelineService } from './api/timeline.service'
export { useUsuarioService } from './api/usuario.service'
export { useJurisprudenciaService } from './api/jurisprudencia.service'
export { usePrazoService } from './api/prazo.service'
