export enum TipoAcaoJurisprudenciaEnum {
  CIVEL = "CIVEL",
  TRABALHISTA = "TRABALHISTA",
  CRIMINAL = "CRIMINAL",
  TRIBUTARIO = "TRIBUTARIO",
  FAMILIA = "FAMILIA",
  CONSUMIDOR = "CONSUMIDOR",
  OUTROS = "OUTROS"
}
